/**
 * Comprehensive Indian States and Official Districts Database
 * Sorted strictly alphabetically (A to Z) with geocoordinates.
 */

const RAW_LOCATIONS: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur",
    "Bapatla",
    "Chittoor",
    "Eluru",
    "Guntur",
    "Kadapa (YSR)",
    "Kakinada",
    "Kurnool",
    "Machilipatnam (Krishna)",
    "Nandyal",
    "Nellore (SPSR Nellore)",
    "Ongole (Prakasam)",
    "Palnadu",
    "Rajahmundry (East Godavari)",
    "Sri Sathya Sai",
    "Srikakulam",
    "Tirupati",
    "Vijayawada (NTR)",
    "Visakhapatnam",
    "Vizianagaram",
  ],
  Bihar: [
    "Arrah (Bhojpur)",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bettiah (West Champaran)",
    "Bhagalpur",
    "Bihar Sharif (Nalanda)",
    "Buxar",
    "Chhapra (Saran)",
    "Darbhanga",
    "Dehri",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Motihari (East Champaran)",
    "Munger",
    "Muzaffarpur",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas (Sasaram)",
    "Saharsa",
    "Samastipur",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali (Hajipur)",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha (Palanpur)",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Gandhinagar",
    "Gir Somnath (Veraval)",
    "Godhra (Panchmahal)",
    "Gondal",
    "Himmatnagar (Sabarkantha)",
    "Jamnagar",
    "Junagadh",
    "Kutch (Bhuj)",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Nadiad (Kheda)",
    "Navsari",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad",
    "Vapi",
  ],
  Haryana: [
    "Ambala",
    "Bahadurgarh (Jhajjar)",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram (Gurgaon)",
    "Hisar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra (Thanesar)",
    "Mahendragarh (Narnaul)",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  Karnataka: [
    "Bagalkote",
    "Ballari",
    "Belagavi",
    "Bengaluru Rural",
    "Bengaluru Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikkamagaluru",
    "Chitradurga",
    "Davanagere",
    "Gadag",
    "Hassan",
    "Haveri",
    "Hosapete (Vijayanagara)",
    "Hubballi-Dharwad",
    "Kalaburagi (Gulbarga)",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mangaluru (Dakshina Kannada)",
    "Mysuru",
    "Raichur",
    "Ramanagara",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Uttara Kannada",
    "Vijayapura (Bijapur)",
    "Yadgir",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam (Kochi)",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  "Madhya Pradesh": [
    "Balaghat",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Gwalior",
    "Hoshangabad (Narmadapuram)",
    "Indore",
    "Jabalpur",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandsaur",
    "Morena",
    "Neemuch",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shajapur",
    "Shivpuri",
    "Singrauli",
    "Ujjain",
    "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Chhatrapati Sambhajinagar (Aurangabad)",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad (Dharashiv)",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal",
  ],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Berhampur (Ganjam)",
    "Bhadrak",
    "Bhubaneswar (Khurda)",
    "Cuttack",
    "Dhenkanal",
    "Jagatsinghpur",
    "Jajpur",
    "Jeypore (Koraput)",
    "Jharsuguda",
    "Kendrapara",
    "Kendujhar",
    "Mayurbhanj (Baripada)",
    "Puri",
    "Rayagada",
    "Rourkela (Sundargarh)",
    "Sambalpur",
  ],
  Punjab: [
    "Abohar (Fazilka)",
    "Amritsar",
    "Barnala",
    "Batala (Gurdaspur)",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Firozpur",
    "Hoshiarpur",
    "Jalandhar",
    "Khanna",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Muktsar",
    "Nawanshahr (SBS Nagar)",
    "Pathankot",
    "Patiala",
    "Phagwara (Kapurthala)",
    "Rupnagar",
    "SAS Nagar (Mohali)",
    "Sangrur",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Dungarpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari (Nagercoil)",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris (Ooty)",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvarur",
    "Tiruvannamalai",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  Telangana: [
    "Adilabad",
    "Hyderabad",
    "Jagtial",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Kothagudem",
    "Mahbubnagar",
    "Mancherial",
    "Medak",
    "Miryalaguda",
    "Nalgonda",
    "Nizamabad",
    "Ramagundam (Peddapalli)",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ayodhya (Faizabad)",
    "Ballia",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Budaun",
    "Deoria",
    "Firozabad",
    "Ghaziabad",
    "Ghazipur",
    "Gorakhpur",
    "Hardoi",
    "Jaunpur",
    "Jhansi",
    "Kanpur",
    "Lakhimpur Kheri",
    "Lucknow",
    "Mathura",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Noida (Gautam Buddha Nagar)",
    "Prayagraj (Allahabad)",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Shahjahanpur",
    "Sitapur",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum (Suri)",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad (Baharampur)",
    "Nadia (Krishnanagar)",
    "North 24 Parganas",
    "Paschim Bardhaman (Durgapur/Asansol)",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "Siliguri",
    "South 24 Parganas",
    "Uttar Dinajpur",
  ],
};

// Guarantee strict alphabetical sorting on both State keys and District lists
export const LOCATIONS: Record<string, string[]> = Object.keys(RAW_LOCATIONS)
  .sort((a, b) => a.localeCompare(b))
  .reduce((acc, state) => {
    acc[state] = [...RAW_LOCATIONS[state]].sort((a, b) => a.localeCompare(b));
    return acc;
  }, {} as Record<string, string[]>);

/** Approximate Coordinates for mapping and distance calculation */
export const DISTRICT_COORDS: Record<string, { lat: number; lng: number }> = {
  // Maharashtra
  Ahmednagar: { lat: 19.0948, lng: 74.748 },
  Akola: { lat: 20.7002, lng: 77.0082 },
  Amravati: { lat: 20.932, lng: 77.7523 },
  Beed: { lat: 18.9891, lng: 75.7601 },
  Bhandara: { lat: 21.1714, lng: 79.6548 },
  Buldhana: { lat: 20.5293, lng: 76.1843 },
  Chandrapur: { lat: 19.9615, lng: 79.2961 },
  "Chhatrapati Sambhajinagar (Aurangabad)": { lat: 19.8762, lng: 75.3433 },
  Dhule: { lat: 20.9042, lng: 74.7749 },
  Gadchiroli: { lat: 20.1809, lng: 80.0028 },
  Gondia: { lat: 21.4598, lng: 80.1961 },
  Hingoli: { lat: 19.7196, lng: 77.1472 },
  Jalgaon: { lat: 21.0077, lng: 75.5626 },
  Jalna: { lat: 19.841, lng: 75.8864 },
  Kolhapur: { lat: 16.705, lng: 74.2433 },
  Latur: { lat: 18.4088, lng: 76.5604 },
  "Mumbai City": { lat: 18.9388, lng: 72.8354 },
  "Mumbai Suburban": { lat: 19.1307, lng: 72.8804 },
  Mumbai: { lat: 19.076, lng: 72.8777 },
  Nagpur: { lat: 21.1458, lng: 79.0882 },
  Nanded: { lat: 19.1383, lng: 77.321 },
  Nandurbar: { lat: 21.3703, lng: 74.2403 },
  Nashik: { lat: 19.9975, lng: 73.7898 },
  "Osmanabad (Dharashiv)": { lat: 18.1856, lng: 76.0419 },
  Palghar: { lat: 19.6967, lng: 72.7655 },
  Parbhani: { lat: 19.2612, lng: 76.7766 },
  Pune: { lat: 18.5204, lng: 73.8567 },
  Raigad: { lat: 18.5158, lng: 73.1812 },
  Ratnagiri: { lat: 16.9902, lng: 73.312 },
  Sangli: { lat: 16.8524, lng: 74.5815 },
  Satara: { lat: 17.6805, lng: 73.9937 },
  Sindhudurg: { lat: 16.1158, lng: 73.7006 },
  Solapur: { lat: 17.6599, lng: 75.9064 },
  Thane: { lat: 19.2183, lng: 72.9781 },
  Wardha: { lat: 20.7453, lng: 78.6022 },
  Washim: { lat: 20.111, lng: 77.1352 },
  Yavatmal: { lat: 20.3888, lng: 78.1204 },

  // Uttar Pradesh
  Agra: { lat: 27.1767, lng: 78.0081 },
  Aligarh: { lat: 27.8974, lng: 78.088 },
  "Ayodhya (Faizabad)": { lat: 26.7922, lng: 82.1998 },
  Bareilly: { lat: 28.367, lng: 79.4304 },
  Ghaziabad: { lat: 28.6692, lng: 77.4538 },
  Gorakhpur: { lat: 26.7606, lng: 83.3732 },
  Jhansi: { lat: 25.4484, lng: 78.5685 },
  Kanpur: { lat: 26.4499, lng: 80.3319 },
  Lucknow: { lat: 26.8467, lng: 80.9462 },
  Mathura: { lat: 27.4924, lng: 77.6737 },
  Meerut: { lat: 28.9845, lng: 77.7064 },
  Moradabad: { lat: 28.8386, lng: 78.7733 },
  "Noida (Gautam Buddha Nagar)": { lat: 28.5355, lng: 77.391 },
  "Prayagraj (Allahabad)": { lat: 25.4358, lng: 81.8463 },
  Saharanpur: { lat: 29.964, lng: 77.546 },
  Varanasi: { lat: 25.3176, lng: 82.9739 },

  // Madhya Pradesh
  Bhopal: { lat: 23.2599, lng: 77.4126 },
  Gwalior: { lat: 26.2183, lng: 78.1828 },
  Indore: { lat: 22.7196, lng: 75.8577 },
  Jabalpur: { lat: 23.1815, lng: 79.9864 },
  Katni: { lat: 23.8343, lng: 80.399 },
  Ratlam: { lat: 23.3315, lng: 75.0367 },
  Rewa: { lat: 24.5362, lng: 81.3037 },
  Sagar: { lat: 23.8388, lng: 78.7378 },
  Satna: { lat: 24.582, lng: 80.8322 },
  Ujjain: { lat: 23.1765, lng: 75.7885 },

  // Gujarat
  Ahmedabad: { lat: 23.0225, lng: 72.5714 },
  Bhavnagar: { lat: 21.7645, lng: 72.1519 },
  Gandhinagar: { lat: 23.2156, lng: 72.6369 },
  Jamnagar: { lat: 22.4707, lng: 70.0577 },
  Junagadh: { lat: 21.5222, lng: 70.4579 },
  Rajkot: { lat: 22.3039, lng: 70.8022 },
  Surat: { lat: 21.1702, lng: 72.8311 },
  Vadodara: { lat: 22.3072, lng: 73.1812 },

  // Karnataka
  "Bengaluru Urban": { lat: 12.9716, lng: 77.5946 },
  "Bengaluru Rural": { lat: 13.2847, lng: 77.534 },
  Belagavi: { lat: 15.8497, lng: 74.4977 },
  "Hubballi-Dharwad": { lat: 15.3647, lng: 75.124 },
  "Kalaburagi (Gulbarga)": { lat: 17.3297, lng: 76.8343 },
  "Mangaluru (Dakshina Kannada)": { lat: 12.9141, lng: 74.856 },
  Mysuru: { lat: 12.2958, lng: 76.6394 },

  // Tamil Nadu
  Chennai: { lat: 13.0827, lng: 80.2707 },
  Coimbatore: { lat: 11.0168, lng: 76.9558 },
  Madurai: { lat: 9.9252, lng: 78.1198 },
  Salem: { lat: 11.6643, lng: 78.146 },
  Tiruchirappalli: { lat: 10.7905, lng: 78.7047 },

  // Rajasthan
  Ajmer: { lat: 26.4499, lng: 74.6399 },
  Bikaner: { lat: 28.0229, lng: 73.3119 },
  Jaipur: { lat: 26.9124, lng: 75.7873 },
  Jodhpur: { lat: 26.2389, lng: 73.0243 },
  Kota: { lat: 25.2138, lng: 75.8648 },
  Udaipur: { lat: 24.5854, lng: 73.7125 },

  // Other Major Cities
  Kolkata: { lat: 22.5726, lng: 88.3639 },
  Patna: { lat: 25.5941, lng: 85.1376 },
  Hyderabad: { lat: 17.385, lng: 78.4867 },
  Ludhiana: { lat: 30.901, lng: 75.8573 },
  Amritsar: { lat: 31.634, lng: 74.8723 },
  "New Delhi": { lat: 28.6139, lng: 77.209 },
  Thiruvananthapuram: { lat: 8.5241, lng: 76.9366 },
  Bhubaneswar: { lat: 20.2961, lng: 85.8245 },
};

export const BUSINESS_ACTIVITIES = [
  "Automobile repair & service station",
  "Beauty parlour / salon",
  "Building materials & cement trading",
  "Dairy & livestock trading",
  "Farm equipment rental & tractor service",
  "Food stall / restaurant / catering",
  "Handicrafts & artisan manufacturing",
  "Hardware & electrical goods store",
  "Kirana / retail grocery shop",
  "Mobile & electronics repair shop",
  "Passenger & commercial transport service",
  "Pharma / medical retail store",
  "Printing press & digital studio",
  "Solar equipment installation & trade",
  "Tailoring boutique & garments",
  "Other micro/small enterprise",
].sort((a, b) => a.localeCompare(b));

export const AGRICULTURE_ACTIVITIES = [
  "Bee keeping & honey processing",
  "Dairy unit (Cow / Buffalo)",
  "Fishery / Aquaculture pond",
  "Floriculture / Greenhouse farming",
  "Goat / Sheep rearing",
  "Mushroom cultivation",
  "Organic vegetable & fruit farming",
  "Poultry farming (Broiler / Layer)",
].sort((a, b) => a.localeCompare(b));
