"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "hi" | "mr" | "gu" | "ta" | "te" | "bn" | "kn";

export interface LanguageOption {
  code: Language;
  label: string;
  native: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", label: "English", native: "English", flag: "🇬🇧" },
  { code: "hi", label: "Hindi", native: "हिन्दी", flag: "🇮🇳" },
  { code: "mr", label: "Marathi", native: "मराठी", flag: "🚩" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી", flag: "🇮🇳" },
  { code: "ta", label: "Tamil", native: "தமிழ்", flag: "🇮🇳" },
  { code: "te", label: "Telugu", native: "తెలుగు", flag: "🇮🇳" },
  { code: "bn", label: "Bengali", native: "বাংলা", flag: "🇮🇳" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ", flag: "🇮🇳" },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_wizard: "Find My Scheme",
    nav_calculator: "EMI Calculator",
    nav_locator: "Partner Locator",
    nav_checklist: "Checklist",
    nav_get_started: "Get Started",

    // Hero
    hero_badge: "✨ Government SC Loan Schemes · Made Simple",
    hero_title_1: "The money is waiting.",
    hero_title_2: "We show you the way to it.",
    hero_desc: "Crores in earmarked government funding for SC entrepreneurs and students goes underutilized every year — simply because people don't know which scheme fits them, what their EMI looks like, or which Channel Partner to walk into. SchemeSaathi fixes all three.",
    hero_cta_find: "Find My Scheme →",
    hero_cta_locate: "Locate Partners Near Me",

    // Stats
    stat_1_val: "₹50 L",
    stat_1_lbl: "max project financing under Term Loan",
    stat_2_val: "6.5%",
    stat_2_lbl: "interest from, among India's cheapest",
    stat_3_val: "100+",
    stat_3_lbl: "Channel Partners you can choose between",
    stat_4_val: "90%",
    stat_4_lbl: "of project cost can be financed",

    // Modules
    mod_badge: "Interactive Tools",
    mod_title: "Three steps between you and your loan",
    mod_sub: "Each step is one module — they hand off to each other automatically.",

    // Wizard
    wiz_step_0: "About You",
    wiz_step_1: "Your Goal",
    wiz_step_2: "Project Cost",
    wiz_step_3: "Background",
    wiz_title_0: "Tell us about yourself",
    wiz_sub_0: "We customize the scheme and nearest channel partners to your district.",
    wiz_state_lbl: "State",
    wiz_state_ph: "Select state…",
    wiz_dist_lbl: "District",
    wiz_dist_ph: "Select district…",
    wiz_dist_wait: "Select a state first",
    wiz_cat_lbl: "Social Category",
    wiz_age_lbl: "Applicant Age",
    wiz_years: "years",

    wiz_title_1: "What do you need the loan for?",
    wiz_sub_1: "Select your loan purpose and specific project activity.",
    wiz_pur_biz: "Business",
    wiz_pur_biz_hint: "Shop, retail, transport, manufacturing",
    wiz_pur_agri: "Agriculture & Allied",
    wiz_pur_agri_hint: "Dairy, poultry, fishery, sheep rearing",
    wiz_pur_edu: "Education",
    wiz_pur_edu_hint: "Professional / technical higher degrees",
    wiz_act_select: "Select Specific Activity / Trade",
    wiz_act_edu_select: "Select Specific Course / Degree",
    wiz_act_ph: "Choose activity…",
    wiz_act_selected: "Selected:",
    wiz_course_loc: "Course Location",
    wiz_course_in: "India 🇮🇳 (₹25L Max)",
    wiz_course_ab: "Abroad ✈️ (₹40L Max)",

    wiz_title_2: "Financial parameters",
    wiz_sub_2: "Government concessional loans finance up to 90% of cost with 10% margin money.",
    wiz_cost_lbl: "Estimated Project Cost",
    wiz_course_cost_lbl: "Total Course Cost",
    wiz_financed_lbl: "Financed (90%):",
    wiz_income_lbl: "Annual Family Income",
    wiz_income_rule: "💡 Income Rule: Family income up to ₹3.00L qualifies for Micro Finance (6.5% interest) and up to ₹5.00L for Term Loan (8%–12.5%).",

    wiz_title_3: "Review & Match",
    wiz_sub_3: "Verify your details before generating your AI loan recommendation.",
    wiz_edu_lbl: "Highest Education Level",
    wiz_edu_ph: "Select education level…",
    wiz_profile_sum: "Profile Summary",
    wiz_sum_loc: "Location:",
    wiz_sum_pur: "Purpose:",
    wiz_sum_cost: "Cost:",
    wiz_sum_inc: "Income:",
    wiz_btn_back: "← Back",
    wiz_btn_continue: "Continue →",
    wiz_btn_submit: "Get Recommendation ✨",
    wiz_btn_analyzing: "Analyzing…",

    // Calculator
    calc_tag: "🧮 Financial Planner",
    calc_title: "EMI & Amortization Calculator",
    calc_sub_rec: "Pre-filled for your scheme — adjust sliders to explore.",
    calc_loan_amt: "Loan Amount",
    calc_rate: "Interest Rate",
    calc_tenure: "Repayment Tenure",
    calc_moratorium: "Moratorium / Grace Period",
    calc_moratorium_check: "Pay simple interest during grace period",
    calc_moratorium_hint: "(drastically lowers total repayment)",
    calc_find_apply: "Find Where To Apply 📍 →",
    calc_monthly_emi: "Your monthly EMI",
    calc_grace_emi: "Monthly EMI after grace period",
    calc_principal: "Principal Loan",
    calc_total_interest: "Total Interest",
    calc_total_repayment: "Total Repayment",
    calc_repay_sched: "Repayment schedule",
    calc_expand: "Expand schedule ▼",
    calc_less: "Show less ▲",

    // Locator
    loc_tag: "📍 Channel Partners",
    loc_title: "Geo-Spatial Channel Partner Locator",
    loc_sub: "Showing nearest authorised branches, sorted by distance.",
    loc_type_lbl: "Type",
    loc_dist_lbl: "District",
    loc_near_me: "📍 Near Me",
    loc_show_npa: "Show high-NPA",
    loc_nearest_badge: "Nearest",
    loc_call: "📞 Call",
    loc_directions: "➤ Directions",

    // Checklist
    chk_tag: "📄 Official Requirements",
    chk_title: "Document Checklist",
    chk_sub: "Everything an authorised Channel Partner asks for. Check off items as you gather them.",
    chk_print: "Print / Save PDF 🖨️",
    chk_mandatory: "Mandatory for Every Scheme",

    // Chatbot
    chat_title: "Ask Saathi AI",
    chat_sub: "Real-Time Government Scheme AI",
    chat_ph: "Ask about schemes, EMIs, or bank branches…",
    chat_send: "Send",
    chat_thinking: "Saathi AI is finding exact schemes…",
    chat_suggested: "💡 Suggested Queries:",
  },

  hi: {
    // Navigation
    nav_home: "मुख्य पृष्ठ",
    nav_wizard: "योजना खोजें",
    nav_calculator: "ईएमआई कैलकुलेटर",
    nav_locator: "पार्टनर लोकेटर",
    nav_checklist: "दस्तावेज़ सूची",
    nav_get_started: "शुरू करें",

    // Hero
    hero_badge: "✨ अनुसूचित जाति (SC) सरकारी ऋण योजनाएं · आसान और सरल",
    hero_title_1: "सरकारी धन उपलब्ध है।",
    hero_title_2: "हम आपको सही रास्ता दिखाते हैं।",
    hero_desc: "अनुसूचित जाति (SC) के उद्यमियों और छात्रों के लिए करोड़ों रुपये का सरकारी फंड हर साल बिना उपयोग के रह जाता है — क्योंकि लोगों को सही योजना, ईएमआई और बैंक शाखा की जानकारी नहीं होती। SchemeSaathi इन तीनों का समाधान करता है।",
    hero_cta_find: "मेरी योजना खोजें →",
    hero_cta_locate: "नजदीकी बैंक खोजें",

    // Stats
    stat_1_val: "₹50 लाख",
    stat_1_lbl: "टर्म लोन के तहत अधिकतम ऋण राशि",
    stat_2_val: "6.5%",
    stat_2_lbl: "न्यूनतम ब्याज दर, भारत में सबसे सस्ती",
    stat_3_val: "100+",
    stat_3_lbl: "अधिकृत चैनल पार्टनर बैंक और संस्थाएं",
    stat_4_val: "90%",
    stat_4_lbl: "परियोजना लागत का 90% सरकारी वित्तपोषण",

    // Modules
    mod_badge: "उपयोगी उपकरण",
    mod_title: "ऋण प्राप्त करने के 3 आसान चरण",
    mod_sub: "प्रत्येक चरण एक-दूसरे से स्वतः जुड़े हुए हैं।",

    // Wizard
    wiz_step_0: "आपके बारे में",
    wiz_step_1: "आपका लक्ष्य",
    wiz_step_2: "परियोजना लागत",
    wiz_step_3: "समीक्षा",
    wiz_title_0: "अपने बारे में बताएं",
    wiz_sub_0: "हम आपके जिले के अनुसार सही योजना और नजदीकी बैंक शाखा की पहचान करते हैं।",
    wiz_state_lbl: "राज्य (State)",
    wiz_state_ph: "राज्य चुनें…",
    wiz_dist_lbl: "जिला (District)",
    wiz_dist_ph: "जिला चुनें…",
    wiz_dist_wait: "पहले राज्य चुनें",
    wiz_cat_lbl: "सामाजिक श्रेणी (Category)",
    wiz_age_lbl: "आवेदक की आयु",
    wiz_years: "वर्ष",

    wiz_title_1: "आपको ऋण किस उद्देश्य के लिए चाहिए?",
    wiz_sub_1: "अपने ऋण का उद्देश्य और विशिष्ट कार्यक्षेत्र चुनें।",
    wiz_pur_biz: "व्यवसाय / व्यापार",
    wiz_pur_biz_hint: "दुकान, खुदरा, परिवहन, विनिर्माण",
    wiz_pur_agri: "कृषि एवं संबद्ध",
    wiz_pur_agri_hint: "डेयरी, मुर्गी पालन, मत्स्य पालन, पशुपालन",
    wiz_pur_edu: "उच्च शिक्षा",
    wiz_pur_edu_hint: "व्यावसायिक एवं तकनीकी उच्च डिग्रियां",
    wiz_act_select: "विशिष्ट गतिविधि / व्यापार चुनें",
    wiz_act_edu_select: "विशिष्ट कोर्स / डिग्री चुनें",
    wiz_act_ph: "गतिविधि चुनें…",
    wiz_act_selected: "चयनित:",
    wiz_course_loc: "कोर्स का स्थान",
    wiz_course_in: "भारत में 🇮🇳 (अधिकतम ₹25 लाख)",
    wiz_course_ab: "विदेश में ✈️ (अधिकतम ₹40 लाख)",

    wiz_title_2: "वित्तीय आवश्यकताएं",
    wiz_sub_2: "सरकारी रियायती ऋण में 90% सरकार देती है और केवल 10% आपका अंशदान होता है।",
    wiz_cost_lbl: "अनुमानित परियोजना लागत",
    wiz_course_cost_lbl: "कोर्स की कुल लागत",
    wiz_financed_lbl: "सरकारी ऋण (90%):",
    wiz_income_lbl: "वार्षिक पारिवारिक आय",
    wiz_income_rule: "💡 आय नियम: ₹3.00 लाख तक की आय पर माइक्रो फाइनेंस (6.5% ब्याज) और ₹5.00 लाख तक टर्म लोन (8%–12.5%) मिलता है।",

    wiz_title_3: "समीक्षा एवं मिलान",
    wiz_sub_3: "अपनी AI ऋण सिफारिश जनरेट करने से पहले विवरण की पुष्टि करें।",
    wiz_edu_lbl: "उच्चतम शिक्षा स्तर",
    wiz_edu_ph: "शिक्षा स्तर चुनें…",
    wiz_profile_sum: "प्रोफ़ाइल सारांश",
    wiz_sum_loc: "स्थान:",
    wiz_sum_pur: "उद्देश्य:",
    wiz_sum_cost: "लागत:",
    wiz_sum_inc: "आय:",
    wiz_btn_back: "← पीछे",
    wiz_btn_continue: "आगे बढ़ें →",
    wiz_btn_submit: "योजना सिफारिश प्राप्त करें ✨",
    wiz_btn_analyzing: "विश्लेषण जारी है…",

    // Calculator
    calc_tag: "🧮 वित्तीय योजनाकार",
    calc_title: "ईएमआई एवं पुनर्भुगतान कैलकुलेटर",
    calc_sub_rec: "आपकी योजना के अनुसार पूर्व-भरी हुई — स्लाइडर से जांचें।",
    calc_loan_amt: "ऋण राशि (Loan Amount)",
    calc_rate: "ब्याज दर (% प्रति वर्ष)",
    calc_tenure: "पुनर्भुगतान अवधि (महीने)",
    calc_moratorium: "मोराटोरियम / छूट अवधि (महीने)",
    calc_moratorium_check: "छूट अवधि के दौरान साधारण ब्याज का भुगतान करें",
    calc_moratorium_hint: "(कुल भुगतान में भारी बचत होती है)",
    calc_find_apply: "आवेदन कहां करें देखें 📍 →",
    calc_monthly_emi: "आपकी मासिक ईएमआई",
    calc_grace_emi: "छूट अवधि के बाद मासिक ईएमआई",
    calc_principal: "मूल ऋण राशि",
    calc_total_interest: "कुल ब्याज",
    calc_total_repayment: "कुल पुनर्भुगतान",
    calc_repay_sched: "पुनर्भुगतान अनुसूची (Repayment Schedule)",
    calc_expand: "अनुसूची देखें ▼",
    calc_less: "छुपाएं ▲",

    // Locator
    loc_tag: "📍 चैनल पार्टनर बैंक",
    loc_title: "नजदीकी अधिकृत बैंक एवं संस्था खोजक",
    loc_sub: "दूरी के अनुसार क्रमबद्ध नजदीकी अधिकृत शाखाएं दिखाई जा रही हैं।",
    loc_type_lbl: "प्रकार",
    loc_dist_lbl: "जिला",
    loc_near_me: "📍 मेरे पास",
    loc_show_npa: "उच्च-NPA दिखाएं",
    loc_nearest_badge: "सबसे पास",
    loc_call: "📞 फोन करें",
    loc_directions: "➤ दिशा-निर्देश",

    // Checklist
    chk_tag: "📄 आधिकारिक आवश्यकताएं",
    chk_title: "आवश्यक दस्तावेज़ सूची (Checklist)",
    chk_sub: "बैंक जाने से पहले इन सभी दस्तावेज़ों की जांच कर लें।",
    chk_print: "प्रिंट / PDF सहेजें 🖨️",
    chk_mandatory: "प्रत्येक योजना के लिए अनिवार्य दस्तावेज़",

    // Chatbot
    chat_title: "साथी AI से पूछें",
    chat_sub: "सरकारी योजना AI सलाहकार",
    chat_ph: "योजनाओं, ईएमआई या बैंक शाखाओं के बारे में पूछें…",
    chat_send: "भेजें",
    chat_thinking: "साथी AI सटीक योजना खोज रहा है…",
    chat_suggested: "💡 सुझाए गए प्रश्न:",
  },

  mr: {
    // Navigation
    nav_home: "मुख्यपृष्ठ",
    nav_wizard: "योजना शोधा",
    nav_calculator: "EMI कॅल्क्युलेटर",
    nav_locator: "पार्टनर लोकेटर",
    nav_checklist: "कागदपत्रे यादी",
    nav_get_started: "सुरू करा",

    // Hero
    hero_badge: "✨ अनुसूचित जाती (SC) शासकीय कर्ज योजना · सोप्या भाषेत",
    hero_title_1: "शासनाचा निधी उपलब्ध आहे.",
    hero_title_2: "आम्ही दाखवतो योग्य मार्ग.",
    hero_desc: "अनुसूचित जातीच्या (SC) उद्योजकांसाठी आणि विद्यार्थ्यांसाठी कोट्यवधी रुपयांचा शासकीय निधी दरवर्षी पडून राहतो — कारण लोकांना योग्य योजना, EMI आणि अधिकृत बँकेची माहिती नसते. SchemeSaathi या तिन्हींची अचूक माहिती देते.",
    hero_cta_find: "माझी योजना शोधा →",
    hero_cta_locate: "जवळची बँक शाखा शोधा",

    // Stats
    stat_1_val: "₹50 लाख",
    stat_1_lbl: "टर्म लोन अंतर्गत कमाल कर्ज मर्यादा",
    stat_2_val: "6.5%",
    stat_2_lbl: "सवलतीचा व्याजदर, भारतातील सर्वात स्वस्त",
    stat_3_val: "100+",
    stat_3_lbl: "अधिकृत चॅनल पार्टनर बँका व संस्था",
    stat_4_val: "90%",
    stat_4_lbl: "प्रकल्प खर्चाच्या 90% शासकीय वित्तपुरवठा",

    // Modules
    mod_badge: "उपयुक्त टूल्स",
    mod_title: "कर्ज मिळवण्याचे 3 सोपे टप्पे",
    mod_sub: "प्रत्येक टप्पा एकमेकांशी आपोआप जोडलेला आहे.",

    // Wizard
    wiz_step_0: "माहिती",
    wiz_step_1: "उद्दिष्ट",
    wiz_step_2: "प्रकल्प खर्च",
    wiz_step_3: "पडताळणी",
    wiz_title_0: "तुमच्याबद्दल सांगा",
    wiz_sub_0: "आम्ही तुमच्या जिल्ह्यानुसार योग्य शासकीय योजना आणि जवळच्या बँकांची माहिती देतो.",
    wiz_state_lbl: "राज्य (State)",
    wiz_state_ph: "राज्य निवडा…",
    wiz_dist_lbl: "जिल्हा (District)",
    wiz_dist_ph: "जिल्हा निवडा…",
    wiz_dist_wait: "आधी राज्य निवडा",
    wiz_cat_lbl: "सामाजिक प्रवर्ग (Category)",
    wiz_age_lbl: "अर्जदाराचे वय",
    wiz_years: "वर्षे",

    wiz_title_1: "तुम्हाला कर्ज कशासाठी हवे आहे?",
    wiz_sub_1: "कर्जाचा हेतू आणि नेमका व्यवसाय प्रकार निवडा.",
    wiz_pur_biz: "व्यवसाय / उद्योग",
    wiz_pur_biz_hint: "दुकान, किरकोळ विक्री, वाहतूक, उत्पादन",
    wiz_pur_agri: "शेती व पूरक व्यवसाय",
    wiz_pur_agri_hint: "दुग्धव्यवसाय, कुक्कुटपालन, मत्स्यपालन, शेळीपालन",
    wiz_pur_edu: "उच्च शिक्षण",
    wiz_pur_edu_hint: "व्यावसायिक व तांत्रिक उच्च पदव्या",
    wiz_act_select: "नेमका व्यवसाय / उपक्रम निवडा",
    wiz_act_edu_select: "नेमका कोर्स / पदवी निवडा",
    wiz_act_ph: "उपक्रम निवडा…",
    wiz_act_selected: "निवडलेले:",
    wiz_course_loc: "शिक्षणाचे ठिकाण",
    wiz_course_in: "भारतात 🇮🇳 (कमाल ₹25 लाख)",
    wiz_course_ab: "परदेशात ✈️ (कमाल ₹40 लाख)",

    wiz_title_2: "आर्थिक तपशील",
    wiz_sub_2: "शासकीय सवलतीच्या कर्जात 90% रक्कम शासन देते आणि फक्त 10% स्वतःचे योगदान लागते.",
    wiz_cost_lbl: "अंदाजे प्रकल्प खर्च",
    wiz_course_cost_lbl: "कोर्सचा एकूण खर्च",
    wiz_financed_lbl: "शासकीय कर्ज (90%):",
    wiz_income_lbl: "वार्षिक कौटुंबिक उत्पन्न",
    wiz_income_rule: "💡 उत्पन्न नियम: ₹3.00 लाखांपर्यंत मायक्रो फायनान्स (6.5% व्याज) आणि ₹5.00 लाखांपर्यंत टर्म लोन (8%–12.5%) मिळते.",

    wiz_title_3: "पुनरावलोकन व AI शिफारस",
    wiz_sub_3: "AI शिफारस मिळवण्यापूर्वी तुमचे तपशील तपासा.",
    wiz_edu_lbl: "उच्चतम शिक्षण",
    wiz_edu_ph: "शिक्षण निवडा…",
    wiz_profile_sum: "प्रोफाइल सारांश",
    wiz_sum_loc: "ठिकाण:",
    wiz_sum_pur: "हेतू:",
    wiz_sum_cost: "खर्च:",
    wiz_sum_inc: "उत्पन्न:",
    wiz_btn_back: "← मागे",
    wiz_btn_continue: "पुढे जा →",
    wiz_btn_submit: "योजना शिफारस मिळवा ✨",
    wiz_btn_analyzing: "विश्लेषण सुरू आहे…",

    // Calculator
    calc_tag: "🧮 आर्थिक नियोजन",
    calc_title: "EMI आणि परतफेड कॅल्क्युलेटर",
    calc_sub_rec: "तुमच्या योजनेनुसार आपोआप भरलेले — स्लायडरने तपासा.",
    calc_loan_amt: "कर्ज रक्कम (Loan Amount)",
    calc_rate: "व्याजदर (% दरसाल)",
    calc_tenure: "परतफेड मुदत (महिने)",
    calc_moratorium: "सवलत कालावधी (मोराटोरियम महिने)",
    calc_moratorium_check: "सवलत काळात फक्त साधे व्याज भरा",
    calc_moratorium_hint: "(एकूण परतफेडीत मोठी बचत होते)",
    calc_find_apply: "अर्ज कुठे करायचा ते पाहा 📍 →",
    calc_monthly_emi: "तुमचा मासिक EMI",
    calc_grace_emi: "सवलत काळानंतर मासिक EMI",
    calc_principal: "मुद्दल कर्ज",
    calc_total_interest: "एकूण व्याज",
    calc_total_repayment: "एकूण परतफेड",
    calc_repay_sched: "मासिक परतफेड वेळापत्रक",
    calc_expand: "तपशील पाहा ▼",
    calc_less: "कमी करा ▲",

    // Locator
    loc_tag: "📍 चॅनल पार्टनर बँका",
    loc_title: "जवळची अधिकृत बँक शाखा शोधक",
    loc_sub: "अंतरावर आधारित सर्वात जवळच्या अधिकृत बँक शाखा.",
    loc_type_lbl: "प्रकार",
    loc_dist_lbl: "जिल्हा",
    loc_near_me: "📍 माझ्या जवळ",
    loc_show_npa: "जास्त NPA दाखवा",
    loc_nearest_badge: "सर्वात जवळ",
    loc_call: "📞 कॉल करा",
    loc_directions: "➤ मार्ग",

    // Checklist
    chk_tag: "📄 अधिकृत कागदपत्रे",
    chk_title: "आवश्यक कागदपत्रांची यादी (Checklist)",
    chk_sub: "बँकेत जाण्यापूर्वी ही सर्व कागदपत्रे तयार ठेवा.",
    chk_print: "प्रिंट / PDF सेव्ह करा 🖨️",
    chk_mandatory: "प्रत्येक योजनेसाठी अनिवार्य कागदपत्रे",

    // Chatbot
    chat_title: "साथी AI ला विचारा",
    chat_sub: "शासकीय योजना AI सल्लागार",
    chat_ph: "योजना, EMI किंवा बँकेबद्दल विचारा…",
    chat_send: "पाठवा",
    chat_thinking: "साथी AI अचूक योजना शोधत आहे…",
    chat_suggested: "💡 सुचवलेले प्रश्न:",
  },

  gu: {
    nav_home: "મુખ્ય પૃષ્ઠ",
    nav_wizard: "યોજના શોધો",
    nav_calculator: "EMI કેલ્ક્યુલેટર",
    nav_locator: "પાર્ટનર લોકેટર",
    nav_checklist: "દસ્તાવેજ યાદી",
    nav_get_started: "શરૂ કરો",
    hero_badge: "✨ અનુસૂચિત જાતિ (SC) સરકારી લોન યોજનાઓ",
    hero_title_1: "સરકારી ભંડોળ ઉપલબ્ધ છે.",
    hero_title_2: "અમે તમને સાચો રસ્તો બતાવીએ છીએ.",
    hero_desc: "SC ઉદ્યોગસાહસિકો અને વિદ્યાર્થીઓ માટે કરોડો રૂપિયાનું સરકારી ફંડ ઉપલબ્ધ છે. SchemeSaathi તમને યોગ્ય યોજના અને બેંક શોધવામાં મદદ કરે છે.",
    hero_cta_find: "મારી યોજના શોધો →",
    hero_cta_locate: "નજીકની બેંક શોધો",
    stat_1_val: "₹50 લાખ",
    stat_1_lbl: "ટર્મ લોન હેઠળ મહત્તમ લોન",
    stat_2_val: "6.5%",
    stat_2_lbl: "ઓછો વ્યાજ દર",
    stat_3_val: "100+",
    stat_3_lbl: "અધિકૃત ચેનલ પાર્ટનર બેંકો",
    stat_4_val: "90%",
    stat_4_lbl: "પ્રોજેક્ટ ખર્ચનું 90% ધિરાણ",
    mod_badge: "સાધનો",
    mod_title: "લોન મેળવવાના 3 સરળ પગલાં",
    mod_sub: "દરેક પગલું એકબીજા સાથે જોડાયેલું છે.",
    wiz_step_0: "તમારી વિગત",
    wiz_step_1: "તમારો ઉદ્દેશ્ય",
    wiz_step_2: "પ્રોજેક્ટ ખર્ચ",
    wiz_step_3: "ચકાસણી",
    wiz_title_0: "તમારી વિગતો આપો",
    wiz_sub_0: "અમે તમારા જિલ્લા મુજબ યોગ્ય યોજના અને નજીકની બેંક શોધીએ છીએ.",
    wiz_state_lbl: "રાજ્ય",
    wiz_state_ph: "રાજ્ય પસંદ કરો…",
    wiz_dist_lbl: "જિલ્લો",
    wiz_dist_ph: "જિલ્લો પસંદ કરો…",
    wiz_dist_wait: "પહેલાં રાજ્ય પસંદ કરો",
    wiz_cat_lbl: "સામાજિક શ્રેણી",
    wiz_age_lbl: "અરજદારની ઉંમર",
    wiz_years: "વર્ષ",
    wiz_title_1: "લોન શેના માટે જોઈએ છે?",
    wiz_sub_1: "તમારો વ્યવસાય પસંદ કરો.",
    wiz_pur_biz: "વેપાર / વ્યવસાય",
    wiz_pur_biz_hint: "દુકાન, પરિવહન, ઉત્પાદન",
    wiz_pur_agri: "કૃષિ અને પશુપાલન",
    wiz_pur_agri_hint: "ડેરી, મરઘાં પાલન, મત્સ્ય પાલન",
    wiz_pur_edu: "ઉચ્ચ શિક્ષણ",
    wiz_pur_edu_hint: "ડિગ્રી અને ડિપ્લોમા કોર્સ",
    wiz_act_select: "પ્રવૃત્તિ પસંદ કરો",
    wiz_act_edu_select: "કોર્સ પસંદ કરો",
    wiz_act_ph: "પસંદ કરો…",
    wiz_act_selected: "પસંદ કરેલ:",
    wiz_course_loc: "સ્થળ",
    wiz_course_in: "ભારતમાં 🇮🇳 (મહત્તમ ₹25L)",
    wiz_course_ab: "વિદેશમાં ✈️ (મહત્તમ ₹40L)",
    wiz_title_2: "નાણાકીય વિગતો",
    wiz_sub_2: "સરકારી લોનમાં 90% સરકાર આપે છે અને માત્ર 10% તમારું રોકાણ હોય છે.",
    wiz_cost_lbl: "અંદાજિત પ્રોજેક્ટ ખર્ચ",
    wiz_course_cost_lbl: "કોર્સનો કુલ ખર્ચ",
    wiz_financed_lbl: "સરકારી લોન (90%):",
    wiz_income_lbl: "વાર્ષિક પારિવારિક આવક",
    wiz_income_rule: "💡 આવક નિયમ: ₹3.00L સુધી માઇક્રો ફાઇનાન્સ (6.5%) અને ₹5.00L સુધી ટર્મ લોન (8%-12.5%).",
    wiz_title_3: "AI ભલામણ",
    wiz_sub_3: "તમારી વિગતો ચકાસો.",
    wiz_edu_lbl: "શિક્ષણ સ્તર",
    wiz_edu_ph: "પસંદ કરો…",
    wiz_profile_sum: "પ્રોફાઇલ સારાંશ",
    wiz_sum_loc: "સ્થળ:",
    wiz_sum_pur: "હેતુ:",
    wiz_sum_cost: "ખર્ચ:",
    wiz_sum_inc: "આવક:",
    wiz_btn_back: "← પાછળ",
    wiz_btn_continue: "આગળ વધો →",
    wiz_btn_submit: "યોજના શોધો ✨",
    wiz_btn_analyzing: "વિશ્લેષણ ચાલુ છે…",
    calc_tag: "🧮 EMI કેલ્ક્યુલેટર",
    calc_title: "EMI અને પુનઃચુકવણી કેલ્ક્યુલેટર",
    calc_sub_rec: "તમારી યોજના અનુસાર આપમેળે ભરેલું.",
    calc_loan_amt: "લોન રકમ",
    calc_rate: "વ્યાજ દર (% p.a.)",
    calc_tenure: "મુદત (મહિના)",
    calc_moratorium: "ગ્રેસ પીરિયડ (મહિના)",
    calc_moratorium_check: "ગ્રેસ પીરિયડ દરમિયાન સાદું વ્યાજ ચૂકવો",
    calc_moratorium_hint: "(મોટી બચત થાય છે)",
    calc_find_apply: "અરજી ક્યાં કરવી 📍 →",
    calc_monthly_emi: "તમારી માસિક EMI",
    calc_grace_emi: "ગ્રેસ પછી માસિક EMI",
    calc_principal: "મુખ્ય લોન",
    calc_total_interest: "કુલ વ્યાજ",
    calc_total_repayment: "કુલ ચુકવણી",
    calc_repay_sched: "ચુકવણી સમયપત્રક",
    calc_expand: "વિગતો જુઓ ▼",
    calc_less: "ઓછું કરો ▲",
    loc_tag: "📍 ચેનલ પાર્ટનર",
    loc_title: "નજીકની બેંક શોધો",
    loc_sub: "અધિકૃત બેંક શાખાઓ.",
    loc_type_lbl: "પ્રકાર",
    loc_dist_lbl: "જિલ્લો",
    loc_near_me: "📍 મારી નજીક",
    loc_show_npa: "હાઈ-NPA બતાવો",
    loc_nearest_badge: "સૌથી નજીક",
    loc_call: "📞 કૉલ",
    loc_directions: "➤ દિશા",
    chk_tag: "📄 દસ્તાવેજો",
    chk_title: "જરૂરી દસ્તાવેજ ચેકલિસ્ટ",
    chk_sub: "અરજી કરતાં પહેલાં આ દસ્તાવેજો તૈયાર રાખો.",
    chk_print: "પ્રિન્ટ / PDF 🖨️",
    chk_mandatory: "ફરજિયાત દસ્તાવેજો",
    chat_title: "સાથી AI ને પૂછો",
    chat_sub: "સરકારી લોન AI સહાયક",
    chat_ph: "યોજના, EMI અથવા બેંક વિશે પૂછો…",
    chat_send: "મોકલો",
    chat_thinking: "સાથી AI વિચારી રહ્યું છે…",
    chat_suggested: "💡 પ્રશ્નો:",
  },

  ta: {
    nav_home: "முகப்பு",
    nav_wizard: "திட்டத்தைக் கண்டறி",
    nav_calculator: "EMI கால்குலேட்டர்",
    nav_locator: "வங்கி கிளைகள்",
    nav_checklist: "ஆவணங்கள்",
    nav_get_started: "தொடங்குங்கள்",
    hero_badge: "✨ SC அரசு கடன் திட்டங்கள் · எளிய வழிகாட்டல்",
    hero_title_1: "அரசு நிதி தயாராக உள்ளது.",
    hero_title_2: "சரியான வழியை நாங்கள் காட்டுகிறோம்.",
    hero_desc: "SC தொழில்முனைவோர் மற்றும் மாணவர்களுக்கான அரசு கடன் திட்டங்கள், EMI கணக்கீடு மற்றும் அருகிலுள்ள வங்கிகளை எளிதாகக் கண்டறியுங்கள்.",
    hero_cta_find: "திட்டம் கண்டறி →",
    hero_cta_locate: "அருகிலுள்ள வங்கிகள்",
    stat_1_val: "₹50 லட்சம்",
    stat_1_lbl: "டெர்ம் லோன் அதிகபட்ச கடன்",
    stat_2_val: "6.5%",
    stat_2_lbl: "குறைந்த வட்டி விகிதம்",
    stat_3_val: "100+",
    stat_3_lbl: "அங்கீகரிக்கப்பட்ட வங்கிகள்",
    stat_4_val: "90%",
    stat_4_lbl: "90% அரசு நிதி உதவி",
    mod_badge: "கருவிகள்",
    mod_title: "கடன் பெற 3 எளிய படிகள்",
    mod_sub: "ஒவ்வொரு படியும் தானாக இணைக்கப்பட்டுள்ளது.",
    wiz_step_0: "சுயவிவரம்",
    wiz_step_1: "நோக்கம்",
    wiz_step_2: "திட்டச் செலவு",
    wiz_step_3: "சரிபார்ப்பு",
    wiz_title_0: "உங்கள் விவரங்களைத் தெரிவிக்கவும்",
    wiz_sub_0: "உங்கள் மாவட்டத்திற்கு ஏற்ற சிறந்த திட்டத்தை நாங்கள் தேர்வு செய்கிறோம்.",
    wiz_state_lbl: "மாநிலம்",
    wiz_state_ph: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்…",
    wiz_dist_lbl: "மாவட்டம்",
    wiz_dist_ph: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்…",
    wiz_dist_wait: "முதலில் மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    wiz_cat_lbl: "சமூகப் பிரிவு",
    wiz_age_lbl: "விண்ணப்பதாரர் வயது",
    wiz_years: "வயது",
    wiz_title_1: "கடன் எதற்காக தேவைப்படுகிறது?",
    wiz_sub_1: "உங்கள் வணிக அல்லது கல்வி நோக்கத்தைத் தேர்ந்தெடுக்கவும்.",
    wiz_pur_biz: "வணிகம் / தொழில்",
    wiz_pur_biz_hint: "கடை, போக்குவரத்து, உற்பத்தி",
    wiz_pur_agri: "விவசாயம் & கால்நடை",
    wiz_pur_agri_hint: "பால் பண்ணை, கோழி பண்ணை, மீன் வளர்ப்பு",
    wiz_pur_edu: "உயர் கல்வி",
    wiz_pur_edu_hint: "தொழில்நுட்ப மற்றும் தொழில்முறை பட்டப்படிப்பு",
    wiz_act_select: "தொழில் வகையைத் தேர்ந்தெடுக்கவும்",
    wiz_act_edu_select: "படிப்பு வகையைத் தேர்ந்தெடுக்கவும்",
    wiz_act_ph: "தேர்ந்தெடு…",
    wiz_act_selected: "தேர்வு:",
    wiz_course_loc: "படிக்கும் இடம்",
    wiz_course_in: "இந்தியா 🇮🇳 (அதிகபட்சம் ₹25L)",
    wiz_course_ab: "வெளிநாடு ✈️ (அதிகபட்சம் ₹40L)",
    wiz_title_2: "நிதித் தேவைகள்",
    wiz_sub_2: "90% அரசு கடன் உதவி, 10% மட்டுமே உங்கள் முதலீடு.",
    wiz_cost_lbl: "மதிப்பிடப்பட்ட திட்ட செலவு",
    wiz_course_cost_lbl: "மொத்த படிப்பு செலவு",
    wiz_financed_lbl: "அரசு கடன் (90%):",
    wiz_income_lbl: "ஆண்டு குடும்ப வருமானம்",
    wiz_income_rule: "💡 வருமான வரம்பு: ₹3L வரை மைக்ரோ ஃபைனான்ஸ் (6.5%), ₹5L வரை டெர்ம் லோன் (8%-12.5%).",
    wiz_title_3: "AI பரிந்துரை",
    wiz_sub_3: "உங்கள் விவரங்களை சரிபார்க்கவும்.",
    wiz_edu_lbl: "கல்வித் தகுதி",
    wiz_edu_ph: "தேர்ந்தெடுக்கவும்…",
    wiz_profile_sum: "விவர சுருக்கம்",
    wiz_sum_loc: "இடம்:",
    wiz_sum_pur: "நோக்கம்:",
    wiz_sum_cost: "செலவு:",
    wiz_sum_inc: "வருமானம்:",
    wiz_btn_back: "← பின்செல்",
    wiz_btn_continue: "தொடர்க →",
    wiz_btn_submit: "பரிந்துரை பெறு ✨",
    wiz_btn_analyzing: "ஆராய்ச்சி செய்கிறது…",
    calc_tag: "🧮 EMI கால்குலேட்டர்",
    calc_title: "EMI மற்றும் திருப்பிச் செலுத்தும் கால்குலேட்டர்",
    calc_sub_rec: "உங்கள் திட்டத்திற்கு ஏற்ப நிரப்பப்பட்டுள்ளது.",
    calc_loan_amt: "கடன் தொகை",
    calc_rate: "வட்டி விகிதம் (% p.a.)",
    calc_tenure: "கால அளவு (மாதங்கள்)",
    calc_moratorium: "அவகாச காலம் (மாதங்கள்)",
    calc_moratorium_check: "அவகாச காலத்தில் எளிய வட்டி செலுத்தவும்",
    calc_moratorium_hint: "(மொத்த தொகையில் சேமிப்பு)",
    calc_find_apply: "விண்ணப்பிக்க வங்கி காண்க 📍 →",
    calc_monthly_emi: "மாதாந்திர EMI",
    calc_grace_emi: "அவகாசத்திற்குப் பின் EMI",
    calc_principal: "அசல் கடன்",
    calc_total_interest: "மொத்த வட்டி",
    calc_total_repayment: "மொத்த திருப்பிச் செலுத்தல்",
    calc_repay_sched: "திருப்பிச் செலுத்தும் அட்டவணை",
    calc_expand: "அட்டவணை விரி ▼",
    calc_less: "குறைக்க ▲",
    loc_tag: "📍 வங்கி கிளைகள்",
    loc_title: "அருகிலுள்ள வங்கி கிளைகள்",
    loc_sub: "தூரத்தின் அடிப்படையில் வரிசைப்படுத்தப்பட்டுள்ளது.",
    loc_type_lbl: "வகை",
    loc_dist_lbl: "மாவட்டம்",
    loc_near_me: "📍 அருகில்",
    loc_show_npa: "உயர்-NPA காட்டு",
    loc_nearest_badge: "மிக அருகில்",
    loc_call: "📞 அழைக்க",
    loc_directions: "➤ வழித்தடம்",
    chk_tag: "📄 ஆவணங்கள்",
    chk_title: "தேவையான ஆவணங்களின் பட்டியல்",
    chk_sub: "வங்கிக்கு செல்லும் முன் இவற்றை சரிபார்க்கவும்.",
    chk_print: "அச்சிடுக / PDF 🖨️",
    chk_mandatory: "கட்டாய ஆவணங்கள்",
    chat_title: "சாதி AI இடம் கேளுங்கள்",
    chat_sub: "அரசு கடன் AI ஆலோசகர்",
    chat_ph: "திட்டங்கள், EMI பற்றி கேளுங்கள்…",
    chat_send: "அனுப்புக",
    chat_thinking: "சிந்திக்கிறது…",
    chat_suggested: "💡 கேள்விகள்:",
  },

  te: {
    nav_home: "హోమ్",
    nav_wizard: "పథకం కనుగొనండి",
    nav_calculator: "EMI కాలిక్యులేటర్",
    nav_locator: "బ్యాంక్ లొకేటర్",
    nav_checklist: "డాక్యుమెంట్ చెక్‌లిస్ట్",
    nav_get_started: "ప్రారంభించండి",
    hero_badge: "✨ SC ప్రభుత్వ రుణ పథకాలు · సులభమైన మార్గదర్శి",
    hero_title_1: "ప్రభుత్వ నిధులు సిద్ధంగా ఉన్నాయి.",
    hero_title_2: "మేము సరైన మార్గాన్ని చూపిస్తాము.",
    hero_desc: "SC పారిశ్రామికవేత్తలు మరియు విద్యార్థుల కోసం ప్రభుత్వ రాయితీ రుణాలు, EMI గణన మరియు సమీప అధీకృత బ్యాంకుల సమాచారం.",
    hero_cta_find: "నా పథకం కనుగొనండి →",
    hero_cta_locate: "సమీప బ్యాంకులు",
    stat_1_val: "₹50 లక్షలు",
    stat_1_lbl: "టర్మ్ లోన్ గరిష్ట పరిమితి",
    stat_2_val: "6.5%",
    stat_2_lbl: "తక్కువ వడ్డీ రేటు",
    stat_3_val: "100+",
    stat_3_lbl: "అధికారిక భాగస్వామ్య బ్యాంకులు",
    stat_4_val: "90%",
    stat_4_lbl: "90% ప్రభుత్వ ఆర్థిక సహాయం",
    mod_badge: "ఉపకరణాలు",
    mod_title: "రుణం పొందడానికి 3 సులభమైన దశలు",
    mod_sub: "ప్రతి దశ స్వయంచాలకంగా అనుసంధానించబడింది.",
    wiz_step_0: "మీ వివరాలు",
    wiz_step_1: "లక్ష్యం",
    wiz_step_2: "ప్రాజెక్ట్ ఖర్చు",
    wiz_step_3: "సమీక్ష",
    wiz_title_0: "మీ గురించి తెలపండి",
    wiz_sub_0: "మీ జిల్లాకు తగిన ఉత్తమ పథకం మరియు బ్యాంకులను గుర్తిస్తాము.",
    wiz_state_lbl: "రాష్ట్రం",
    wiz_state_ph: "రాష్ట్రాన్ని ఎంచుకోండి…",
    wiz_dist_lbl: "జిల్లా",
    wiz_dist_ph: "జిల్లాను ఎంచుకోండి…",
    wiz_dist_wait: "ముందుగా రాష్ట్రాన్ని ఎంచుకోండి",
    wiz_cat_lbl: "సామాజిక వర్గం",
    wiz_age_lbl: "దరఖాస్తుదారుడి వయస్సు",
    wiz_years: "సంవత్సరాలు",
    wiz_title_1: "రుణం దేనికోసం అవసరం?",
    wiz_sub_1: "మీ వ్యాపార లేదా విద్యా లక్ష్యాన్ని ఎంచుకోండి.",
    wiz_pur_biz: "వ్యాపారం / పరిశ్రమ",
    wiz_pur_biz_hint: "దుకాణం, రవాణా, తయారీ",
    wiz_pur_agri: "వ్యవసాయం & పాడిపరిశ్రమ",
    wiz_pur_agri_hint: "డైరీ, పౌల్ట్రీ, మత్స్య పరిశ్రమ, గొర్రెల పెంపకం",
    wiz_pur_edu: "ఉన్నత విద్య",
    wiz_pur_edu_hint: "వృత్తిపరమైన మరియు సాంకేతిక డిగ్రీలు",
    wiz_act_select: "నిర్దిష్ట కార్యాచరణను ఎంచుకోండి",
    wiz_act_edu_select: "కోర్సును ఎంచుకోండి",
    wiz_act_ph: "ఎంచుకోండి…",
    wiz_act_selected: "ఎంచుకున్నది:",
    wiz_course_loc: "కోర్సు ప్రదేశం",
    wiz_course_in: "భారతదేశంలో 🇮🇳 (గరిష్టంగా ₹25L)",
    wiz_course_ab: "విదేశాలలో ✈️ (గరిష్టంగా ₹40L)",
    wiz_title_2: "ఆర్థిక అవసరాలు",
    wiz_sub_2: "90% ప్రభుత్వ రుణం, 10% మాత్రమే మీ పెట్టుబడి.",
    wiz_cost_lbl: "అంచనా ప్రాజెక్ట్ ఖర్చు",
    wiz_course_cost_lbl: "మొత్తం కోర్సు ఖర్చు",
    wiz_financed_lbl: "ప్రభుత్వ రుణం (90%):",
    wiz_income_lbl: "వార్షిక కుటుంబ ఆదాయం",
    wiz_income_rule: "💡 ఆదాయ పరిమితి: ₹3L వరకు మైక్రో ఫైనాన్స్ (6.5%), ₹5L వరకు టర్మ్ లోన్ (8%-12.5%).",
    wiz_title_3: "AI సిఫార్సు",
    wiz_sub_3: "వివరాలను ధృవీకరించండి.",
    wiz_edu_lbl: "విద్యార్హత",
    wiz_edu_ph: "ఎంచుకోండి…",
    wiz_profile_sum: "సారాంశం",
    wiz_sum_loc: "ప్రదేశం:",
    wiz_sum_pur: "లక్ష్యం:",
    wiz_sum_cost: "ఖర్చు:",
    wiz_sum_inc: "ఆదాయం:",
    wiz_btn_back: "← వెనుకకు",
    wiz_btn_continue: "కొనసాగించండి →",
    wiz_btn_submit: "సిఫార్సు పొందండి ✨",
    wiz_btn_analyzing: "విశ్లేషిస్తోంది…",
    calc_tag: "🧮 EMI కాలిక్యులేటర్",
    calc_title: "EMI మరియు తిరిగి చెల్లింపు కాలిక్యులేటర్",
    calc_sub_rec: "మీ పథకానికి అనుగుణంగా స్వయంచాలకంగా పూరించబడింది.",
    calc_loan_amt: "రుణ మొత్తం",
    calc_rate: "వడ్డీ రేటు (% p.a.)",
    calc_tenure: "కాలపరిమితి (నెలలు)",
    calc_moratorium: "మొరటోరియం వ్యవధి (నెలలు)",
    calc_moratorium_check: "మొరటోరియం సమయంలో సాధారణ వడ్డీని చెల్లించండి",
    calc_moratorium_hint: "(మొత్తం చెల్లింపులో భారీ ఆదా)",
    calc_find_apply: "దరఖాస్తు చేయడానికి బ్యాంక్ 📍 →",
    calc_monthly_emi: "మీ నెలవారీ EMI",
    calc_grace_emi: "వ్యవధి తర్వాత EMI",
    calc_principal: "అసలు రుణం",
    calc_total_interest: "మొత్తం వడ్డీ",
    calc_total_repayment: "మొత్తం తిరిగి చెల్లింపు",
    calc_repay_sched: "తిరిగి చెల్లింపు షెడ్యూల్",
    calc_expand: "షెడ్యూల్ చూడండి ▼",
    calc_less: "తగ్గించండి ▲",
    loc_tag: "📍 బ్యాంక్ శాఖలు",
    loc_title: "సమీప బ్యాంక్ లొకేటర్",
    loc_sub: "దూరం ఆధారంగా క్రమబద్ధీకరించబడింది.",
    loc_type_lbl: "రకం",
    loc_dist_lbl: "జిల్లా",
    loc_near_me: "📍 నా సమీపంలో",
    loc_show_npa: "హై-NPA చూపించు",
    loc_nearest_badge: "అత్యంత సమీపం",
    loc_call: "📞 కాల్",
    loc_directions: "➤ రూట్",
    chk_tag: "📄 పత్రాలు",
    chk_title: "అవసరమైన పత్రాల జాబితా",
    chk_sub: "బ్యాంకుకు వెళ్లే ముందు వీటిని సిద్ధం చేసుకోండి.",
    chk_print: "ప్రింట్ / PDF 🖨️",
    chk_mandatory: "తప్పనిసరి పత్రాలు",
    chat_title: "సాథీ AI ని అడగండి",
    chat_sub: "ప్రభుత్వ పథకాల AI సలహాదారు",
    chat_ph: "పథకాలు, EMI ల గురించి అడగండి…",
    chat_send: "పంపండి",
    chat_thinking: "ఆలోచిస్తోంది…",
    chat_suggested: "💡 సూచించిన ప్రశ్నలు:",
  },

  bn: {
    nav_home: "হোম",
    nav_wizard: "স্কিম খুঁজুন",
    nav_calculator: "ইএমআই ক্যালকুলেটর",
    nav_locator: "পার্টনার ব্যাঙ্ক",
    nav_checklist: "নথিপত্র তালিকা",
    nav_get_started: "শুরু করুন",
    hero_badge: "✨ তফশিলি জাতি (SC) সরকারি ঋণ প্রকল্প",
    hero_title_1: "সরকারি তহবিল প্রস্তুত আছে।",
    hero_title_2: "আমরা আপনাকে সঠিক পথ দেখাই।",
    hero_desc: "SC উদ্যোক্তা ও শিক্ষার্থীদের জন্য সরকারি ঋণ প্রকল্প, ইএমআই হিসাব এবং নিকটবর্তী ব্যাঙ্ক খোঁজার সহজ প্ল্যাটফর্ম।",
    hero_cta_find: "স্কিম খুঁজুন →",
    hero_cta_locate: "নিকটবর্তী ব্যাঙ্ক খুঁজুন",
    stat_1_val: "₹৫০ লাখ",
    stat_1_lbl: "টার্ম লোনের সর্বোচ্চ সীমা",
    stat_2_val: "৬.৫%",
    stat_2_lbl: "স্বল্প সুদের হার",
    stat_3_val: "১০০+",
    stat_3_lbl: "অনুমোদিত ব্যাঙ্ক পার্টনার",
    stat_4_val: "৯০%",
    stat_4_lbl: "প্রকল্পের ৯০% সরকারি অর্থায়ন",
    mod_badge: "টুলস",
    mod_title: "ঋণ পাওয়ার ৩টি সহজ ধাপ",
    mod_sub: "প্রতিটি ধাপ একে অপরের সাথে সংযুক্ত।",
    wiz_step_0: "আপনার তথ্য",
    wiz_step_1: "আপনার লক্ষ্য",
    wiz_step_2: "প্রকল্প খরচ",
    wiz_step_3: "যাচাই",
    wiz_title_0: "আপনার সম্পর্কে বলুন",
    wiz_sub_0: "আমরা আপনার জেলার উপযুক্ত স্কিম ও ব্যাঙ্ক খুঁজে দেব।",
    wiz_state_lbl: "রাজ্য",
    wiz_state_ph: "রাজ্য নির্বাচন করুন…",
    wiz_dist_lbl: "জেলা",
    wiz_dist_ph: "জেলা নির্বাচন করুন…",
    wiz_dist_wait: "প্রথমে রাজ্য বাছুন",
    wiz_cat_lbl: "সামাজিক বিভাগ",
    wiz_age_lbl: "আবেদনকারীর বয়স",
    wiz_years: "বছর",
    wiz_title_1: "ঋণের উদ্দেশ্য কী?",
    wiz_sub_1: "আপনার ব্যবসার ধরন নির্বাচন করুন।",
    wiz_pur_biz: "ব্যবসা / বাণিজ্য",
    wiz_pur_biz_hint: "দোকান, পরিবহন, উৎপাদন",
    wiz_pur_agri: "কৃষি ও পশুপালন",
    wiz_pur_agri_hint: "ডেয়ারি, পোল্ট্রি, মৎস্য চাষ",
    wiz_pur_edu: "উচ্চ শিক্ষা",
    wiz_pur_edu_hint: "কারিগরি ও পেশাদার ডিগ্রি",
    wiz_act_select: "নির্দিষ্ট কাজ বেছে নিন",
    wiz_act_edu_select: "কোর্স বেছে নিন",
    wiz_act_ph: "বেছে নিন…",
    wiz_act_selected: "নির্বাচিত:",
    wiz_course_loc: "পড়ার স্থান",
    wiz_course_in: "ভারতে 🇮🇳 (সর্বোচ্চ ₹২৫L)",
    wiz_course_ab: "বিদেশে ✈️ (সর্বোচ্চ ₹৪০L)",
    wiz_title_2: "আর্থিক তথ্য",
    wiz_sub_2: "৯০% সরকারি ঋণ, মাত্র ১০% আপনার নিজস্ব বিনিয়োগ।",
    wiz_cost_lbl: "আনুমানিক প্রকল্প খরচ",
    wiz_course_cost_lbl: "মোট কোর্স খরচ",
    wiz_financed_lbl: "সরকারি ঋণ (৯০%):",
    wiz_income_lbl: "বার্ষিক পারিবারিক আয়",
    wiz_income_rule: "💡 আয়ের নিয়ম: ₹৩L পর্যন্ত মাইক্রো ফাইন্যান্স (৬.৫%), ₹৫L পর্যন্ত টার্ম লোন (৮%-১২.৫%)।",
    wiz_title_3: "AI সুপারিশ",
    wiz_sub_3: "তথ্য যাচাই করুন।",
    wiz_edu_lbl: "শিক্ষাগত যোগ্যতা",
    wiz_edu_ph: "বাছুন…",
    wiz_profile_sum: "সারাংশ",
    wiz_sum_loc: "স্থান:",
    wiz_sum_pur: "উদ্দেশ্য:",
    wiz_sum_cost: "খরচ:",
    wiz_sum_inc: "আয়:",
    wiz_btn_back: "← পেছনে",
    wiz_btn_continue: "এগিয়ে যান →",
    wiz_btn_submit: "সুপারিশ পান ✨",
    wiz_btn_analyzing: "বিশ্লেষণ হচ্ছে…",
    calc_tag: "🧮 ইএমআই ক্যালকুলেটর",
    calc_title: "ইএমআই ও ঋণ পরিশোধ ক্যালকুলেটর",
    calc_sub_rec: "আপনার স্কিম অনুযায়ী পূরণ করা হয়েছে।",
    calc_loan_amt: "ঋণের পরিমাণ",
    calc_rate: "সুদের হার (% বার্ষিক)",
    calc_tenure: "মেয়াদ (মাস)",
    calc_moratorium: "গ্রেস পিরিয়ড (মাস)",
    calc_moratorium_check: "গ্রেস পিরিয়ডে সরল সুদ প্রদান করুন",
    calc_moratorium_hint: "(মোট খরচে বড় সঞ্চয়)",
    calc_find_apply: "আবেদনের ব্যাঙ্ক খুঁজুন 📍 →",
    calc_monthly_emi: "আপনার মাসিক ইএমআই",
    calc_grace_emi: "গ্রেসের পর মাসিক ইএমআই",
    calc_principal: "আসল ঋণ",
    calc_total_interest: "মোট সুদ",
    calc_total_repayment: "মোট পরিশোধ",
    calc_repay_sched: "পরিশোধের সময়সূচী",
    calc_expand: "তালিকা দেখুন ▼",
    calc_less: "সংক্ষিপ্ত করুন ▲",
    loc_tag: "📍 ব্যাঙ্ক পার্টনার",
    loc_title: "নিকটবর্তী ব্যাঙ্ক লোকেটর",
    loc_sub: "দূরত্ব অনুযায়ী সাজানো শাখা।",
    loc_type_lbl: "ধরন",
    loc_dist_lbl: "জেলা",
    loc_near_me: "📍 আমার কাছে",
    loc_show_npa: "উচ্চ-NPA দেখুন",
    loc_nearest_badge: "সবচেয়ে কাছে",
    loc_call: "📞 কল",
    loc_directions: "➤ পথনির্দেশ",
    chk_tag: "📄 নথিপত্র",
    chk_title: "প্রয়োজনীয় নথিপত্রের তালিকা",
    chk_sub: "ব্যাঙ্কে যাওয়ার আগে এই নথিপত্র প্রস্তুত রাখুন।",
    chk_print: "প্রিন্ট / PDF 🖨️",
    chk_mandatory: "বাধ্যতামূলক নথি",
    chat_title: "সাথী AI-কে জিজ্ঞাসা করুন",
    chat_sub: "সরকারি ঋণ AI সহকারী",
    chat_ph: "স্কিম, ইএমআই বা ব্যাঙ্ক সম্পর্কে জানুন…",
    chat_send: "পাঠান",
    chat_thinking: "ভাবছে…",
    chat_suggested: "💡 প্রস্তাবিত প্রশ্ন:",
  },

  kn: {
    nav_home: "ಮುಖಪುಟ",
    nav_wizard: "ಯೋಜನೆ ಹುಡುಕಿ",
    nav_calculator: "EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    nav_locator: "ಬ್ಯಾಂಕ್ ಲೊಕೇಟರ್",
    nav_checklist: "ದಾಖಲೆಗಳ ಪಟ್ಟಿ",
    nav_get_started: "ಪ್ರಾರಂಭಿಸಿ",
    hero_badge: "✨ ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ಸರ್ಕಾರಿ ಸಾಲ ಯೋಜನೆಗಳು",
    hero_title_1: "ಸರ್ಕಾರಿ ಅನುದಾನ ಸಿದ್ಧವಾಗಿದೆ.",
    hero_title_2: "ನಾವು ಸರಿಯಾದ ದಾರಿಯನ್ನು ತೋರಿಸುತ್ತೇವೆ.",
    hero_desc: "SC ಉದ್ಯಮಿಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ರಿಯಾಯಿತಿ ಸಾಲಗಳು, EMI ಲೆಕ್ಕಾಚಾರ ಮತ್ತು ಹತ್ತಿರದ ಅಧಿಕೃತ ಬ್ಯಾಂಕ್‌ಗಳ ಮಾಹಿತಿ.",
    hero_cta_find: "ಯೋಜನೆ ಹುಡುಕಿ →",
    hero_cta_locate: "ಹತ್ತಿರದ ಬ್ಯಾಂಕ್ ಹುಡುಕಿ",
    stat_1_val: "₹50 ಲಕ್ಷ",
    stat_1_lbl: "ಟರ್ಮ್ ಲೋನ್ ಗರಿಷ್ಠ ಮಿತಿ",
    stat_2_val: "6.5%",
    stat_2_lbl: "ಕಡಿಮೆ ಬಡ್ಡಿದರ",
    stat_3_val: "100+",
    stat_3_lbl: "ಅಧಿಕೃತ ಪಾಲುದಾರ ಬ್ಯಾಂಕುಗಳು",
    stat_4_val: "90%",
    stat_4_lbl: "90% ಸರ್ಕಾರಿ ಆರ್ಥಿಕ ನೆರವು",
    mod_badge: "ಉಪಕರಣಗಳು",
    mod_title: "ಸಾಲ ಪಡೆಯಲು 3 ಸುಲಭ ಹಂತಗಳು",
    mod_sub: "ಪ್ರತಿ ಹಂತವೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಂಪರ್ಕಗೊಂಡಿದೆ.",
    wiz_step_0: "ನಿಮ್ಮ ಮಾಹಿತಿ",
    wiz_step_1: "ಉದ್ದೇಶ",
    wiz_step_2: "ಯೋಜನಾ ವೆಚ್ಚ",
    wiz_step_3: "ಪರಿಶೀಲನೆ",
    wiz_title_0: "ನಿಮ್ಮ ಬಗ್ಗೆ ತಿಳಿಸಿ",
    wiz_sub_0: "ನಿಮ್ಮ ಜಿಲ್ಲೆಗೆ ಸೂಕ್ತವಾದ ಯೋಜನೆ ಮತ್ತು ಬ್ಯಾಂಕ್‌ಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.",
    wiz_state_lbl: "ರಾಜ್ಯ",
    wiz_state_ph: "ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ…",
    wiz_dist_lbl: "ಜಿಲ್ಲೆ",
    wiz_dist_ph: "ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ…",
    wiz_dist_wait: "ಮೊದಲು ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ",
    wiz_cat_lbl: "ಸಾಮಾಜಿಕ ವರ್ಗ",
    wiz_age_lbl: "ಅರ್ಜಿದಾರರ ವಯಸ್ಸು",
    wiz_years: "ವರ್ಷಗಳು",
    wiz_title_1: "ಸಾಲ ಯಾವುದಕ್ಕಾಗಿ ಬೇಕು?",
    wiz_sub_1: "ನಿಮ್ಮ ವ್ಯಾಪಾರ ಅಥವಾ ಶಿಕ್ಷಣ ಉದ್ದೇಶ ಆಯ್ಕೆಮಾಡಿ.",
    wiz_pur_biz: "ವ್ಯಾಪಾರ / ಉದ್ದಿಮೆ",
    wiz_pur_biz_hint: "ಅಂಗಡಿ, ಸಾರಿಗೆ, ಉತ್ಪಾದನೆ",
    wiz_pur_agri: "ಕೃಷಿ ಮತ್ತು ಪಶುಸಂಗೋಪನೆ",
    wiz_pur_agri_hint: "ಡೈರಿ, ಕೋಳಿ ಸಾಕಾಣಿಕೆ, ಮೀನುಗಾರಿಕೆ",
    wiz_pur_edu: "ಉನ್ನತ ಶಿಕ್ಷಣ",
    wiz_pur_edu_hint: "ತಾಂತ್ರಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಪದವಿಗಳು",
    wiz_act_select: "ನಿರ್ದಿಷ್ಟ ಚಟುವಟಿಕೆ ಆಯ್ಕೆಮಾಡಿ",
    wiz_act_edu_select: "ಕೋರ್ಸ್ ಆಯ್ಕೆಮಾಡಿ",
    wiz_act_ph: "ಆಯ್ಕೆಮಾಡಿ…",
    wiz_act_selected: "ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ:",
    wiz_course_loc: "ಸ್ಥಳ",
    wiz_course_in: "ಭಾರತದಲ್ಲಿ 🇮🇳 (ಗರಿಷ್ಠ ₹25L)",
    wiz_course_ab: "ವಿದೇಶದಲ್ಲಿ ✈️ (ಗರಿಷ್ಠ ₹40L)",
    wiz_title_2: "ಹಣಕಾಸಿನ ಮಾಹಿತಿ",
    wiz_sub_2: "90% ಸರ್ಕಾರಿ ಸಾಲ, ಕೇವಲ 10% ನಿಮ್ಮ ಸ್ವಂತ ಹೂಡಿಕೆ.",
    wiz_cost_lbl: "ಅಂದಾಜು ಯೋಜನಾ ವೆಚ್ಚ",
    wiz_course_cost_lbl: "ಒಟ್ಟು ಕೋರ್ಸ್ ವೆಚ್ಚ",
    wiz_financed_lbl: "ಸರ್ಕಾರಿ ಸಾಲ (90%):",
    wiz_income_lbl: "ವಾರ್ಷಿಕ ಕುಟುಂಬದ ಆದಾಯ",
    wiz_income_rule: "💡 ಆದಾಯ ನಿಯಮ: ₹3L ವರೆಗೆ ಮೈಕ್ರೋ ಫೈನಾನ್ಸ್ (6.5%), ₹5L ವರೆಗೆ ಟರ್ಮ್ ಲೋನ್ (8%-12.5%).",
    wiz_title_3: "AI ಶಿಫಾರಸು",
    wiz_sub_3: "ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    wiz_edu_lbl: "ವಿದ್ಯಾರ್ಹತೆ",
    wiz_edu_ph: "ಆಯ್ಕೆಮಾಡಿ…",
    wiz_profile_sum: "ವಿವರ ಸಾರಾಂಶ",
    wiz_sum_loc: "ಸ್ಥಳ:",
    wiz_sum_pur: "ಉದ್ದೇಶ:",
    wiz_sum_cost: "ವೆಚ್ಚ:",
    wiz_sum_inc: "ಆದಾಯ:",
    wiz_btn_back: "← ಹಿಂದಕ್ಕೆ",
    wiz_btn_continue: "ಮುಂದುವರಿಯಿರಿ →",
    wiz_btn_submit: "ಶಿಫಾರಸು ಪಡೆಯಿರಿ ✨",
    wiz_btn_analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…",
    calc_tag: "🧮 EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    calc_title: "EMI ಮತ್ತು ಮರುಪಾವತಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    calc_sub_rec: "ನಿಮ್ಮ ಯೋಜನೆಗೆ ಅನುಗುಣವಾಗಿ ಭರ್ತಿ ಮಾಡಲಾಗಿದೆ.",
    calc_loan_amt: "ಸಾಲದ ಮೊತ್ತ",
    calc_rate: "ಬಡ್ಡಿದರ (% p.a.)",
    calc_tenure: "ಅವಧಿ (ತಿಂಗಳು)",
    calc_moratorium: "ರಿಯಾಯಿತಿ ಅವಧಿ (ತಿಂಗಳು)",
    calc_moratorium_check: "ರಿಯಾಯಿತಿ ಅವಧಿಯಲ್ಲಿ ಸರಳ ಬಡ್ಡಿ ಪಾವತಿಸಿ",
    calc_moratorium_hint: "(ಒಟ್ಟು ಮರುಪಾವತಿಯಲ್ಲಿ ಭಾರಿ ಉಳಿತಾಯ)",
    calc_find_apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಬ್ಯಾಂಕ್ 📍 →",
    calc_monthly_emi: "ನಿಮ್ಮ ಮಾಸಿಕ EMI",
    calc_grace_emi: "ಅವಧಿಯ ನಂತರದ EMI",
    calc_principal: "ಅಸಲು ಸಾಲ",
    calc_total_interest: "ಒಟ್ಟು ಬಡ್ಡಿ",
    calc_total_repayment: "ಒಟ್ಟು ಮರುಪಾವತಿ",
    calc_repay_sched: "ಮರುಪಾವತಿ ವೇಳಾಪಟ್ಟಿ",
    calc_expand: "ವೇಳಾಪಟ್ಟಿ ನೋಡಿ ▼",
    calc_less: "ಕಡಿಮೆ ಮಾಡಿ ▲",
    loc_tag: "📍 ಬ್ಯಾಂಕ್ ಶಾಖೆಗಳು",
    loc_title: "ಹತ್ತಿರದ ಬ್ಯಾಂಕ್ ಲೊಕೇಟರ್",
    loc_sub: "ದೂರದ ಆಧಾರದ ಮೇಲೆ ಜೋಡಿಸಲಾದ ಶಾಖೆಗಳು.",
    loc_type_lbl: "ವಿಧ",
    loc_dist_lbl: "ಜಿಲ್ಲೆ",
    loc_near_me: "📍 ನನ್ನ ಹತ್ತಿರ",
    loc_show_npa: "ಹೈ-NPA ತೋರಿಸಿ",
    loc_nearest_badge: "ಅತ್ಯಂತ ಹತ್ತಿರ",
    loc_call: "📞 ಕರೆ",
    loc_directions: "➤ ನಿರ್ದೇಶನ",
    chk_tag: "📄 ದಾಖಲೆಗಳು",
    chk_title: "ಅಗತ್ಯ ದಾಖಲೆಗಳ ಪಟ್ಟಿ",
    chk_sub: "ಬ್ಯಾಂಕ್‌ಗೆ ಹೋಗುವ ಮುನ್ನ ಇವುಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಿಕೊಳ್ಳಿ.",
    chk_print: "ಮುದ್ರಿಸಿ / PDF 🖨️",
    chk_mandatory: "ಕಡ್ಡಾಯ ದಾಖಲೆಗಳು",
    chat_title: "ಸಾಥಿ AI ಕೇಳಿ",
    chat_sub: "ಸರ್ಕಾರಿ ಸಾಲ AI ಸಹಾಯಕ",
    chat_ph: "ಯೋಜನೆಗಳು, EMI ಕುರಿತು ಕೇಳಿ…",
    chat_send: "ಕಳುಹಿಸಿ",
    chat_thinking: "ಯೋಚಿಸುತ್ತಿದೆ…",
    chat_suggested: "💡 ಸಲಹೆ ಪ್ರಶ್ನೆಗಳು:",
  },
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("schemesaathi-lang") as Language;
    if (saved && TRANSLATIONS[saved]) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    try {
      localStorage.setItem("schemesaathi-lang", newLang);
    } catch {}
  };

  const t = (key: string): string => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
